import { Employee } from "../redux/employeeSlice";

export const useMockData = true;

export const mockEmployees: Employee[] = [
  {
    firstName: "Sabrina",
    lastName: "Affane",
    dateOfBirth: "1990-01-15",
    startDate: "2022-06-01",
    department: "Sales",
    street: "123 Market St",
    city: "New York",
    state: "NY",
    zipCode: 10001,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    dateOfBirth: "1985-08-30",
    startDate: "2021-03-15",
    department: "Marketing",
    street: "456 Broadway",
    city: "Los Angeles",
    state: "CA",
    zipCode: 90012,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    dateOfBirth: "1979-12-01",
    startDate: "2020-10-05",
    department: "Engineering",
    street: "789 Tech Ave",
    city: "Seattle",
    state: "WA",
    zipCode: 98101,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    dateOfBirth: "1988-04-20",
    startDate: "2019-01-11",
    department: "HR",
    street: "12 Pine Rd",
    city: "Chicago",
    state: "IL",
    zipCode: 60605,
  },
  {
    firstName: "Laura",
    lastName: "Wilson",
    dateOfBirth: "1992-07-09",
    startDate: "2023-05-19",
    department: "Finance",
    street: "98 Oak Ave",
    city: "Boston",
    state: "MA",
    zipCode: 60605,
  },
  {
    firstName: "Robert",
    lastName: "Davis",
    dateOfBirth: "1983-03-17",
    startDate: "2021-08-01",
    department: "IT",
    street: "34 Elm St",
    city: "Austin",
    state: "TX",
    zipCode: 73301,
  },
  {
    firstName: "Emma",
    lastName: "Martinez",
    dateOfBirth: "1991-10-12",
    startDate: "2022-11-30",
    department: "Sales",
    street: "21 Main St",
    city: "Denver",
    state: "CO",
    zipCode: 80203,
  },
  {
    firstName: "David",
    lastName: "Anderson",
    dateOfBirth: "1986-09-24",
    startDate: "2020-04-10",
    department: "Engineering",
    street: "65 River Rd",
    city: "San Francisco",
    state: "CA",
    zipCode: 94105,
  },
  {
    firstName: "Olivia",
    lastName: "Thomas",
    dateOfBirth: "1994-06-21",
    startDate: "2018-09-15",
    department: "Marketing",
    street: "77 Cedar Ln",
    city: "Portland",
    state: "OR",
    zipCode: 97205,
  },
  {
    firstName: "James",
    lastName: "Jackson",
    dateOfBirth: "1980-02-02",
    startDate: "2023-01-01",
    department: "HR",
    street: "5 Birch St",
    city: "Philadelphia",
    state: "PA",
    zipCode: 19103,
  },
  {
    firstName: "Isabella",
    lastName: "White",
    dateOfBirth: "1993-12-25",
    startDate: "2021-07-07",
    department: "Finance",
    street: "300 Pine Blvd",
    city: "San Diego",
    state: "CA",
    zipCode: 92101,
  },
  {
    firstName: "William",
    lastName: "Harris",
    dateOfBirth: "1987-11-11",
    startDate: "2017-02-14",
    department: "IT",
    street: "40 Lake Dr",
    city: "Miami",
    state: "FL",
    zipCode: 33101,
  },
  {
    firstName: "Mia",
    lastName: "Clark",
    dateOfBirth: "1995-08-08",
    startDate: "2019-12-05",
    department: "Sales",
    street: "10 Bay St",
    city: "Dallas",
    state: "TX",
    zipCode: 75201,
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    dateOfBirth: "1982-05-30",
    startDate: "2020-06-06",
    department: "Engineering",
    street: "75 Maple Ave",
    city: "Phoenix",
    state: "AZ",
    zipCode: 85001,
  },
  {
    firstName: "Sophia",
    lastName: "Lee",
    dateOfBirth: "1990-03-22",
    startDate: "2018-03-03",
    department: "Marketing",
    street: "9 Hill St",
    city: "Charlotte",
    state: "NC",
    zipCode: 28202,
  },
  {
    firstName: "Benjamin",
    lastName: "Walker",
    dateOfBirth: "1978-01-18",
    startDate: "2023-09-10",
    department: "HR",
    street: "44 Green St",
    city: "Indianapolis",
    state: "IN",
    zipCode: 46204,
  },
  {
    firstName: "Charlotte",
    lastName: "Young",
    dateOfBirth: "1989-07-04",
    startDate: "2022-02-20",
    department: "Finance",
    street: "500 Sunset Blvd",
    city: "Las Vegas",
    state: "NV",
    zipCode: 89101,
  },
  {
    firstName: "Logan",
    lastName: "Allen",
    dateOfBirth: "1991-04-27",
    startDate: "2021-11-11",
    department: "IT",
    street: "3 Ocean Dr",
    city: "Baltimore",
    state: "MD",
    zipCode: 21201,
  },
  {
    firstName: "Amelia",
    lastName: "King",
    dateOfBirth: "1996-10-10",
    startDate: "2019-09-09",
    department: "Sales",
    street: "66 Island Ave",
    city: "Detroit",
    state: "MI",
    zipCode: 48201,
  },
  {
    firstName: "Jacob",
    lastName: "Wright",
    dateOfBirth: "1984-09-01",
    startDate: "2020-12-12",
    department: "Engineering",
    street: "32 Capitol St",
    city: "Atlanta",
    state: "GA",
    zipCode: 30303,
  },
  {
    firstName: "Evelyn",
    lastName: "Scott",
    dateOfBirth: "1987-06-06",
    startDate: "2023-04-04",
    department: "Marketing",
    street: "88 Forest Dr",
    city: "Minneapolis",
    state: "MN",
    zipCode: 55401,
  },
  {
    firstName: "Henry",
    lastName: "Green",
    dateOfBirth: "1992-11-29",
    startDate: "2021-05-15",
    department: "HR",
    street: "19 Horizon Way",
    city: "Kansas City",
    state: "MO",
    zipCode: 64101,
  },
  {
    firstName: "Abigail",
    lastName: "Baker",
    dateOfBirth: "1986-12-19",
    startDate: "2020-07-07",
    department: "Finance",
    street: "55 Cloud St",
    city: "Nashville",
    state: "TN",
    zipCode: 37201,
  },
  {
    firstName: "Sebastian",
    lastName: "Nelson",
    dateOfBirth: "1983-05-14",
    startDate: "2018-08-08",
    department: "IT",
    street: "24 Valley Rd",
    city: "Columbus",
    state: "OH",
    zipCode: 43004,
  },
  {
    firstName: "Ella",
    lastName: "Carter",
    dateOfBirth: "1990-02-02",
    startDate: "2022-10-10",
    department: "Sales",
    street: "67 Ridge St",
    city: "Milwaukee",
    state: "WI",
    zipCode: 53202,
  },
  {
    firstName: "Matthew",
    lastName: "Mitchell",
    dateOfBirth: "1977-03-03",
    startDate: "2017-05-05",
    department: "Engineering",
    street: "101 Tech Park",
    city: "Salt Lake City",
    state: "UT",
    zipCode: 84101,
  },
  {
    firstName: "Grace",
    lastName: "Perez",
    dateOfBirth: "1995-01-01",
    startDate: "2020-01-20",
    department: "Marketing",
    street: "400 Creative Ave",
    city: "Raleigh",
    state: "NC",
    zipCode: 27601,
  },
  {
    firstName: "Joseph",
    lastName: "Roberts",
    dateOfBirth: "1981-04-14",
    startDate: "2019-02-02",
    department: "HR",
    street: "22 Admin St",
    city: "Omaha",
    state: "NE",
    zipCode: 68102,
  },
  {
    firstName: "Chloe",
    lastName: "Turner",
    dateOfBirth: "1993-03-17",
    startDate: "2021-01-01",
    department: "Finance",
    street: "29 Willow Ave",
    city: "Richmond",
    state: "VA",
    zipCode: 23220,
  },
];
